### ISSUE TITLE
Guests cannot change email (should they even be allowed to?)

### ISSUE THREAD

**Issue by svengit** [owncloud/guests#174]
Hi,

right now guest users can change their email address in the settings menu. Confirmation mail is send and after clicking the link a small message 'Email changed successfully' is displayed and a 'email adress changed'-Email is send out.
Yet, the email is still the same and the log shows an error for the whole action (I don't quite understand why the interface shows success and the log shows errors, but that's another topic):

> {"reqId":"We70uuB-NVvIJ1OGYNZAFAAAAAw","level":3,"time":"2017-10-24T08:07:22+00:00","remoteAddr":"X.X.X.X","user":"--","app":"user_ldap","method":"POST","url":"\/index.php\/login","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name on ldaps:\\\/\\\/ldap.org.org:636\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(117): OCA\\\\User_LDAP\\\\User_LDAP->getLDAPUserByLoginName('email@provide.org')\\n#1 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(79): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(140): OCA\\\\User_LDAP\\\\User_Proxy->walkBackends('email@provide.org', 'checkPassword', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(194): OCA\\\\User_LDAP\\\\Proxy->handleRequest('email@provide.org', 'checkPassword', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(215): OCA\\\\User_LDAP\\\\User_Proxy->checkPassword(*** sensitive parameters replaced ***)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(467): OC\\\\User\\\\Manager->checkPassword(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(301): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(207): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#9 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(307): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(928): OC\\\\Route\\\\Router->match('\\\/login')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":101}"}

Furthermore I think guests shouldn't be allowed to change their email at all. Since the guest should be able to change his/her password and language and be able to add app passwords, disabling the settings all together won't be an option. It would be nice if the 'change email' button simply showed 'guests cannot change their email' or something like that.

**Comment by PVince81** [comment]
Good point. We need to find a way to block changing emails in the UI and backend for guest users.

cc @pmaier1

**Comment by mmattel** [comment]
For the reference, admins beeing able to access the commandline can change the users eMail/username, core https://github.com/owncloud/core/pull/30540 user:modify command.
I do not know if this has an impact...

**Comment by PVince81** [comment]
for guests I think the email address is used as user id and also it is set as that user id's email address. so even if the admin changes the email address, this won't affect the user id. so the guest must still use their old user id which is the old email address to login

**Comment by PVince81** [comment]
I wonder if we should rather user randomly generated user ids / uuid here... this would make it possible to change the email address.

**Comment by mmattel** [comment]
randomly is hard to remember,
what about to take the recipients name of the eMail address as username?
``carla.a@foobar.dot`` -> ``carla.a``
and if already existing, adding a ``_number`` where number is starting with 1 and counting up.
already existing ``carla.a`` —> ``carla.a_1``

**Comment by PVince81** [comment]
> randomly is hard to remember

doesn't matter because the user can always login with an email address when set

**Comment by mmattel** [comment]
from a technically point of view this is correct.
from a standard users point of view...

**Comment by PVince81** [comment]
> from a standard users point of view...

from a standard user's point of view it is nice being able to change the email address in the personal settings and use exactly that new email address for logging in

any other issues ?

**Comment by mmattel** [comment]
no 😄

**Comment by PVince81** [comment]
so we have two possible approaches here, coming back to the original report:

1) let guests set email addresses by fixing the bug
or
2) prevent guests to set email address officially by showing a message in the UI

**Comment by VicDeo** [comment]
I haven't check with stable10 but it is possible to change email with owncloud master

**Comment by pmaier1** [comment]
> so we have two possible approaches here, coming back to the original report:

I think it makes sense to bind guests to their mail address. If you need long-term exchange with a user that can change their password you can add a "real" user. Guests are thought to be used for mid-term external sharing and should not necessarily be "transferable" in a sense of they should be bound to the mail address the inviting user entered. In other words: The inviting, "real" user stays in control.
